language: node_js
node_js:
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
addons:
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN
script: npm test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
